### ISSUE TITLE
link to stimulus documentation and guide

### ISSUE THREAD

**Issue by andrzejsliwa** [komposable/komponent#31]
would be great to link to stimulus documentation and guide from readme

**Comment by Spone** [comment]
Hi Andrzej,

first of all thanks for your contribution on the stimulus integration!

There is already a link here: https://github.com/komposable/komponent#stimulus-integration

Do you think we should add more links? I think it's best to link only to the repository since other URLs may change at some point.

**Comment by andrzejsliwa** [comment]
Hi Hans, I miss link, thx!
